force-app/main/default/objects/Guest__c/Guest__c.object-meta.xml
<CustomObject>
    <label>Guest</label>
    <nameField>
        <displayFormat>G-{0000}</displayFormat>
        <label>Guest Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Guests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Guest__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <label>Company</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guest__c/fields/Firstname__c.field-meta.xml
<CustomField>
    <fullName>Firstname__c</fullName>
    <label>Firstname</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Guest__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Host</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Guests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Guest__c/fields/Lastname__c.field-meta.xml
<CustomField>
    <fullName>Lastname__c</fullName>
    <label>Lastname</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CallBadgeSystem.cls
public class CallBadgeSystem {

    @InvocableMethod(label='Invokes a call to the remote badge system' description='Creates a badge in the remote using a REST call')
    public static void invokeapexcallout(List<Guest__c> guests) 
    {
        //Soql request
        //List<Guest__c> guests = [select id, name, firstname__c, lastname__c, company__c, host__r.firstname, host__r.lastname from guest__c where Id = :guestId]
        for  (Guest__c guest : guests)
        {
            FutureCallBadgeSystem.apexcallout(guest.id,
                                              guest.firstname__c,
                                              guest.lastname__c,
                                              guest.company__c, 
                                              guest.host__r.FirstName, 
                                              guest.host__r.LastName);
        } 
        
    }
}